import base64
import re
import datetime
from io import open
import os
import zlib

# Converts rust wasm files into html script tags
# Finds any .wasm files generated by wasm-pack in the pkg directory.
# Creates .wasm.html.part files which contain code to be pasted into the target
# html file.
# The exported functions are available in the browser as
# window.wasmExports.MY_FUNCTION();

# see
# https://dzone.com/articles/webassembly-wasmfiddle-and-inline-webassembly-modu
# and
# https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Memory
# htmlPartTemplate = """

# let wasm;

# async function load(module, imports) {

#         const instance = await WebAssembly.instantiate(module, imports);

#         if (instance instanceof WebAssembly.Instance) {
#             return { instance, module };

#         } else {
#             return instance;
#         }
# }

# export async function initWasmBlsSdk() {
# var b = "";
# %s
#     var input = pako.inflate(base64ToUint8Array(b));
#     const imports = {};

#     const { instance, module } = await load(await input, imports);

#     wasm = instance.exports;
#     initWasmBlsSdk.__wbindgen_wasm_module = module;

#     return wasm;
# }

# """

htmlPartTemplate1 = """

    var __wbindgen_throw = function(arg0, arg1) {
        throw new Error(getStringFromWasm0(arg0, arg1));
    };

"""

htmlPartTemplate2 = """
    
export async function initWasmBlsSdk() {

    wasm = retasmFunc;
    init.__wbindgen_wasm_module = retasmFunc;
    return retasmFunc;
}

"""


def injectJsFile(location):
    # read the wasm binary
    f = open(location, "rb")
    fileBytes = []
    try:
        fileBytes = f.read()
    finally:
        f.close()
    # remove exports from wasm2js output
    fileBytes = fileBytes.replace(b"export ", b"// export")
    fileBytes = fileBytes.replace(b"import { __wbindgen_throw } from 'wbg';", b"")
    # put the js code into a template
    htmlPart = htmlPartTemplate1
    htmlPart += fileBytes.decode("utf-8") 
    htmlPart += htmlPartTemplate2
    # save to js file
    newLocation = location + ".html.part"
    f = open(newLocation, "w")
    f.write(htmlPart)
    f.close()
    print("wasm converted to html.part file: %s" % newLocation)



# Find wasm files.
# When compiled with wasm-pack these files appear in the pkg directory
# Then save the converted wasm to file pkg/<NAME>.html.part
pkgDir = "pkg"
for root, dirs, files in os.walk(pkgDir):
    for filename in files:
        name, ext = os.path.splitext(filename)
        if filename == "threshold_crypto_wasm_bridge_bg.js":
            location = os.path.join(root, filename)
            injectJsFile(location)

# This script generates the html file.
# It removes script and style tags and replaces with the file content.
# It also adds wasm content.


page = ""

# Script tags

to_remove_from_wasm_bridge = [
    """
    if (typeof input === 'undefined') {
        input = new URL('threshold_crypto_wasm_bridge_bg.wasm', import.meta.url);
    }
""",
    """
    if (typeof input === 'string' || (typeof Request === 'function' && input instanceof Request) || (typeof URL === 'function' && input instanceof URL)) {
        input = fetch(input);
    }
"""

]

scripts = [
    'html/js-sdk-only/constants.js',
    'html/js-sdk-only/convert.js',
    'html/js-sdk-only/wasm_helpers.js',
    'pkg/threshold_crypto_wasm_bridge.js'
]

for script in scripts:
    s = open(script, "r", encoding="utf-8")
    scriptContent = s.read()
    s.close()
    if script == 'pkg/threshold_crypto_wasm_bridge.js':
        for to_remove in to_remove_from_wasm_bridge:
            scriptContent = scriptContent.replace(to_remove, '')
        # make methods private in JSdoc
        scriptContent = scriptContent.replace("/**", "/**\n* @private")

    page += scriptContent + "\n"


# wasm tag
# TODO a bit too much hardcoding here
f = open("pkg/threshold_crypto_wasm_bridge_bg.js.html.part")
wasmHtml = f.read()
f.close()
page += wasmHtml + "\n"

# Write the standalone file

standaloneFilename = 'bls-sdk.js'
f = open(standaloneFilename, 'w', encoding="utf-8")
f.write(page)
f.close()

print("%s standalone js file created" % datetime.datetime.now())
print("%s see %s" % (datetime.datetime.now(), standaloneFilename))
